package com.bliss.aimemorysearch.indexing;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

/** Cheap, conservative gate that runs before content extraction and model inference. */
public final class FileIndexingPolicy {
    private static final long LARGE_FILE_BYTES = 512L * 1024L;
    private static final int SAMPLE_BYTES = 24 * 1024;

    public Evaluation evaluate(File file) {
        if (file == null || !file.isFile() || !isSampleableText(file.getName())) {
            return Evaluation.index();
        }
        List<String> signals = new ArrayList<>();
        if (file.length() >= LARGE_FILE_BYTES) signals.add("large_file");
        if (hasGeneratedPathSegment(file)) signals.add("generated_output_path");
        try {
            String sample = sample(file).toLowerCase(Locale.ROOT);
            if (hasGeneratorDeclaration(sample)) signals.add("generator_declaration");
            if (isMarkupHeavy(sample)) signals.add("markup_heavy");
            if (hasLowProseDensity(sample)) signals.add("low_prose_density");
        } catch (IOException ignored) {
            return Evaluation.index(); // Classification is deliberately fail-open.
        }
        boolean declarationWithCorroboration = signals.contains("generator_declaration")
                && signals.size() >= 2;
        boolean corroboratedWeakSignals = signals.size() >= 3
                && signals.contains("large_file")
                && (signals.contains("markup_heavy")
                || signals.contains("low_prose_density"));
        if (declarationWithCorroboration || corroboratedWeakSignals) {
            return Evaluation.skip("low_value_machine_generated", signals);
        }
        return Evaluation.index(signals);
    }

    private static boolean isSampleableText(String name) {
        String lower = name.toLowerCase(Locale.ROOT);
        return lower.endsWith(".txt") || lower.endsWith(".html")
                || lower.endsWith(".htm") || lower.endsWith(".xml")
                || lower.endsWith(".json") || lower.endsWith(".csv")
                || lower.endsWith(".md") || lower.endsWith(".rtf");
    }

    private static boolean hasGeneratedPathSegment(File file) {
        String[] segments = file.getAbsolutePath().replace('\\', '/')
                .toLowerCase(Locale.ROOT).split("/");
        for (String segment : segments) {
            if (segment.equals("build") || segment.equals("dist") || segment.equals("target")
                    || segment.equals("out") || segment.equals("cache")
                    || segment.equals("tmp") || segment.equals("temp")
                    || segment.equals("generated") || segment.equals("node_modules")
                    || segment.equals("__pycache__")) return true;
        }
        return false;
    }

    private static String sample(File file) throws IOException {
        try (RandomAccessFile input = new RandomAccessFile(file, "r")) {
            long length = input.length();
            StringBuilder result = new StringBuilder(SAMPLE_BYTES * 3);
            readAt(input, 0, result);
            if (length > SAMPLE_BYTES * 2L) readAt(input, length / 2L, result);
            if (length > SAMPLE_BYTES) readAt(input, Math.max(0, length - SAMPLE_BYTES), result);
            return result.toString();
        }
    }

    private static void readAt(RandomAccessFile input, long offset, StringBuilder output)
            throws IOException {
        input.seek(offset);
        byte[] bytes = new byte[SAMPLE_BYTES];
        int count = input.read(bytes);
        if (count > 0) output.append(new String(bytes, 0, count, StandardCharsets.UTF_8));
    }

    private static boolean hasGeneratorDeclaration(String sample) {
        return sample.contains("automatically generated")
                || sample.contains("auto-generated")
                || sample.contains("machine generated")
                || sample.contains("generated file")
                || (sample.contains("generated by") && sample.contains("do not edit"));
    }

    private static boolean isMarkupHeavy(String sample) {
        if (sample.length() < 1000) return false;
        int angleCharacters = 0;
        int closingTags = 0;
        for (int i = 0; i < sample.length(); i++) {
            char character = sample.charAt(i);
            if (character == '<' || character == '>') angleCharacters++;
            if (i + 1 < sample.length() && character == '<' && sample.charAt(i + 1) == '/') {
                closingTags++;
            }
        }
        return closingTags >= 20 && angleCharacters * 100L / sample.length() >= 3;
    }

    private static boolean hasLowProseDensity(String sample) {
        if (sample.length() < 2000) return false;
        int words = 0;
        int identifierLike = 0;
        for (String token : sample.split("\\s+")) {
            if (token.length() < 3) continue;
            words++;
            if (token.indexOf('/') >= 0 || token.indexOf('\\') >= 0
                    || token.indexOf('_') >= 0 || token.indexOf('=') >= 0
                    || token.indexOf('<') >= 0 || token.indexOf('>') >= 0) identifierLike++;
        }
        return words >= 100 && identifierLike * 100L / words >= 45;
    }

    public static final class Evaluation {
        private final boolean shouldIndex;
        private final String skipReason;
        private final List<String> signals;

        private Evaluation(boolean shouldIndex, String skipReason, List<String> signals) {
            this.shouldIndex = shouldIndex;
            this.skipReason = skipReason;
            this.signals = Collections.unmodifiableList(new ArrayList<>(signals));
        }
        public boolean shouldIndex() { return shouldIndex; }
        public String skipReason() { return skipReason; }
        public List<String> signals() { return signals; }
        private static Evaluation index() { return index(Collections.emptyList()); }
        private static Evaluation index(List<String> signals) {
            return new Evaluation(true, "", signals);
        }
        private static Evaluation skip(String reason, List<String> signals) {
            return new Evaluation(false, reason, signals);
        }
    }
}
