bundleId=ai-search
displayNameKey=ai_package_bundle_ai_search
descriptionKey=ai_package_bundle_ai_search_description
packageIds=core-model-embedding,core-model-e5,core-model-clip-text,core-model-clip-vision
